# Generated by Django 6.0.6 on 2026-06-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=200, verbose_name='Persona')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto total')),
                ('debt_type', models.CharField(choices=[('OWE', 'Yo debo'), ('OWED', 'Me deben')], max_length=4, verbose_name='Tipo')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Interés anual %')),
                ('note', models.TextField(blank=True, verbose_name='Nota')),
                ('is_settled', models.BooleanField(default=False, verbose_name='Saldada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Deuda',
                'verbose_name_plural': 'Deudas',
                'ordering': ['is_settled', '-date'],
            },
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('note', models.TextField(blank=True, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pago de deuda',
                'verbose_name_plural': 'Pagos de deudas',
                'ordering': ['-date'],
            },
        ),
    ]
