# Generated by Django 6.0.6 on 2026-06-06 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debts', '0001_initial'),
        ('finances', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='colony',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.colony', verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='debt',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.currency', verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='debtpayment',
            name='debt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='debts.debt', verbose_name='Deuda'),
        ),
    ]
