# Generated by Django 6.0.6 on 2026-06-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha límite'),
        ),
    ]
