# Generated by Django 6.0.6 on 2026-06-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0003_debt_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='is_settled',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Saldada'),
        ),
    ]
