# Generated by Django 6.0.6 on 2026-06-22 14:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_add_goal_to_transaction'),
        ('users', '0002_alter_colony_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='colony',
            name='auto_create_debt_transactions',
            field=models.BooleanField(default=False, verbose_name='Crear gasto al pagar deuda'),
        ),
        migrations.AddField(
            model_name='colony',
            name='auto_create_split_transactions',
            field=models.BooleanField(default=False, verbose_name='Crear gasto en splits'),
        ),
        migrations.AddField(
            model_name='colony',
            name='budget_alert_threshold',
            field=models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)], verbose_name='Umbral de alerta de presupuesto (%)'),
        ),
        migrations.AddField(
            model_name='colony',
            name='default_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colony_defaults', to='finances.currency', verbose_name='Moneda por defecto'),
        ),
    ]
