# Generated by Django 6.0.6 on 2026-07-25 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_colony_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='colony',
            name='debt_show_days',
            field=models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Mostrar deudas con deadline en (días)'),
        ),
    ]
