# Generated by Django 6.0.6 on 2026-08-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_colony_debt_show_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='colony',
            name='require_funds_for_conversion',
            field=models.BooleanField(default=True, help_text='Impide convertir más de lo que tenés disponible en esa moneda', verbose_name='Exigir fondos para convertir'),
        ),
    ]
