# Generated by Django 6.0.6 on 2026-08-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_colony_require_funds_for_conversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='colony',
            name='tab_bar_config',
            field=models.JSONField(blank=True, default=list, verbose_name='Barra inferior (PWA)'),
        ),
    ]
