# Generated by Django 6.0.6 on 2026-09-13 01:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_colony_tab_bar_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='colony',
            name='ant_expense_income_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Tope relativo al ingreso mensual. El umbral efectivo es el menor de ambos', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.10')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Gasto hormiga: % del ingreso'),
        ),
        migrations.AddField(
            model_name='colony',
            name='ant_expense_max_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000.00'), help_text='Tope absoluto por transacción para considerarla gasto hormiga', max_digits=12, verbose_name='Gasto hormiga: monto máximo'),
        ),
        migrations.AddField(
            model_name='colony',
            name='ant_expense_min_count',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Gasto hormiga: mínimo de transacciones'),
        ),
    ]
