# Generated by Django 5.0.14 on 2026-06-04 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto objetivo')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Progreso actual')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Fecha límite')),
                ('color', models.CharField(default='#C4943A', max_length=7, verbose_name='Color')),
                ('is_achieved', models.BooleanField(default=False, verbose_name='Alcanzada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.currency', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ['-is_achieved', 'deadline', 'name'],
            },
        ),
    ]
