# Generated by Django 6.0.6 on 2026-07-30 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0007_alter_transaction_date_alter_transaction_type'),
        ('users', '0004_colony_debt_show_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto total')),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Dejar vacío para calcular automático', max_digits=12, null=True, verbose_name='Monto por cuota')),
                ('installments_count', models.PositiveIntegerField(verbose_name='Cantidad de cuotas')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('auto_debit', models.BooleanField(default=True, verbose_name='Débito automático')),
                ('is_completed', models.BooleanField(db_index=True, default=False, verbose_name='Completada')),
                ('note', models.TextField(blank=True, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.category', verbose_name='Categoría')),
                ('colony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.colony', verbose_name='Colonia')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.currency', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Compra en cuotas',
                'verbose_name_plural': 'Compras en cuotas',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Número de cuota')),
                ('due_date', models.DateField(db_index=True, verbose_name='Fecha de vencimiento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('is_paid', models.BooleanField(db_index=True, default=False, verbose_name='Pagada')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.transaction', verbose_name='Transacción')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='installments.installmentpurchase', verbose_name='Compra')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['due_date', 'number'],
                'unique_together': {('purchase', 'number')},
            },
        ),
    ]
