# Generated by Django 5.0.14 on 2026-06-04 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('cycle', models.CharField(choices=[('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual'), ('YEARLY', 'Anual')], default='MONTHLY', max_length=10, verbose_name='Ciclo')),
                ('next_date', models.DateField(verbose_name='Próximo cobro')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.category', verbose_name='Categoría')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.currency', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['next_date', 'name'],
            },
        ),
    ]
