# Generated by Django 6.0.6 on 2026-06-10 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_alter_transaction_type'),
        ('subscriptions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='Fecha de cobro')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pagado')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription', verbose_name='Suscripción')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_payment', to='finances.transaction', verbose_name='Transacción')),
            ],
            options={
                'verbose_name': 'Pago de suscripción',
                'verbose_name_plural': 'Pagos de suscripciones',
                'ordering': ['-due_date'],
            },
        ),
    ]
