# Generated by Django 6.0.6 on 2026-06-10 12:35

from django.db import migrations


def create_payments_for_existing(apps, schema_editor):
    Subscription = apps.get_model('subscriptions', 'Subscription')
    SubscriptionPayment = apps.get_model('subscriptions', 'SubscriptionPayment')
    for sub in Subscription.objects.filter(is_active=True):
        SubscriptionPayment.objects.get_or_create(
            subscription=sub,
            due_date=sub.next_date,
            defaults={'is_paid': False},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionpayment'),
    ]

    operations = [
        migrations.RunPython(create_payments_for_existing, migrations.RunPython.noop),
    ]
