# Generated by Django 6.0.6 on 2026-06-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_create_existing_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='due_date',
            field=models.DateField(db_index=True, verbose_name='Fecha de cobro'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Pagado'),
        ),
    ]
