# Generated by Django 6.0.6 on 2026-07-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_subscription_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='auto_debit',
            field=models.BooleanField(default=True, verbose_name='Débito automático'),
        ),
    ]
