# Generated by Django 6.0.6 on 2026-09-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscription_auto_debit'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_variable',
            field=models.BooleanField(default=False, verbose_name='Costo variable'),
        ),
    ]
