# Generated by Django 6.0.6 on 2026-07-30 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0007_alter_transaction_date_alter_transaction_type'),
        ('users', '0004_colony_debt_show_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('cycle', models.CharField(choices=[('WEEKLY', 'Semanal'), ('BIWEEKLY', 'Quincenal'), ('MONTHLY', 'Mensual'), ('BIMONTHLY', 'Bimestral'), ('YEARLY', 'Anual')], default='MONTHLY', max_length=10, verbose_name='Ciclo')),
                ('day_of_month', models.PositiveIntegerField(blank=True, help_text='1-31, solo para ciclo mensual/bimestral', null=True, verbose_name='Día del mes')),
                ('day_of_week', models.PositiveIntegerField(blank=True, help_text='1=Lun..7=Dom, solo para ciclo semanal/quincenal', null=True, verbose_name='Día de la semana')),
                ('next_date', models.DateField(verbose_name='Próximo cobro')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('note', models.TextField(blank=True, help_text='Se copiará a cada transacción generada', verbose_name='Nota')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.category', verbose_name='Categoría')),
                ('colony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.colony', verbose_name='Colonia')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.currency', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Gasto recurrente',
                'verbose_name_plural': 'Gastos recurrentes',
                'ordering': ['next_date', 'name'],
            },
        ),
    ]
