# Generated by Django 6.0.6 on 2026-06-06 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('members', models.JSONField(default=list, verbose_name='Miembros')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SplitExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto total')),
                ('paid_by', models.CharField(max_length=200, verbose_name='Pagado por')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('shares', models.JSONField(default=dict, verbose_name='División')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.currency', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Gasto compartido',
                'verbose_name_plural': 'Gastos compartidos',
                'ordering': ['-date'],
            },
        ),
    ]
