# Generated by Django 6.0.6 on 2026-06-06 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('splits', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitgroup',
            name='colony',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.colony', verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='splitexpense',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='splits.splitgroup', verbose_name='Grupo'),
        ),
    ]
