# Generated by Django 6.0.6 on 2026-09-04 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_alter_transaction_reserve'),
        ('splits', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitgroup',
            name='payment_preferences',
            field=models.JSONField(default=dict, verbose_name='Preferencias de pago'),
        ),
        migrations.CreateModel(
            name='SplitPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.CharField(max_length=200, verbose_name='Pagó')),
                ('payee', models.CharField(max_length=200, verbose_name='Recibió')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.currency', verbose_name='Moneda')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='splits.splitgroup', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Pago de deuda',
                'verbose_name_plural': 'Pagos de deudas',
                'ordering': ['-date'],
            },
        ),
    ]
