# Generated by Django 6.0.6 on 2026-06-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Límite mensual')),
                ('month', models.IntegerField(verbose_name='Mes')),
                ('year', models.IntegerField(verbose_name='Año')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-year', '-month', 'category__name'],
            },
        ),
    ]
