# Generated by Django 5.0.14 on 2026-06-04 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Límite mensual')),
                ('month', models.IntegerField(verbose_name='Mes')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('category', models.ForeignKey(limit_choices_to={'type': 'EXPENSE'}, on_delete=django.db.models.deletion.CASCADE, to='finances.category', verbose_name='Categoría')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.currency', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-year', '-month', 'category__name'],
                'unique_together': {('category', 'month', 'year')},
            },
        ),
    ]
