# Generated by Django 5.0.14 on 2026-06-04 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('type', models.CharField(choices=[('INCOME', 'Ingreso'), ('EXPENSE', 'Gasto')], max_length=7, verbose_name='Tipo')),
                ('icon', models.CharField(blank=True, default='📦', max_length=10, verbose_name='Ícono')),
                ('color', models.CharField(blank=True, default='#A07858', max_length=7, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Código')),
                ('symbol', models.CharField(max_length=5, verbose_name='Símbolo')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('rate_to_base', models.DecimalField(decimal_places=4, default=1.0, help_text='Tasa respecto a la moneda base (ARS=1.0)', max_digits=10)),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('color', models.CharField(blank=True, default='#8A6348', max_length=7, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INCOME', '💰 Ingreso'), ('EXPENSE', '💸 Gasto')], max_length=7, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('custom_tags', models.JSONField(blank=True, default=list, verbose_name='Etiquetas personalizadas')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('note', models.TextField(blank=True, verbose_name='Nota')),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='Comprobante')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Es recurrente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(limit_choices_to={'type': 'EXPENSE'}, on_delete=django.db.models.deletion.PROTECT, to='finances.category', verbose_name='Categoría')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.currency', verbose_name='Moneda')),
                ('tags', models.ManyToManyField(blank=True, to='finances.tag', verbose_name='Etiquetas')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
