# Generated by Django 6.0.6 on 2026-06-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='package', max_length=50, verbose_name='Ícono'),
        ),
    ]
