# Generated by Django 6.0.6 on 2026-06-22 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_alter_transaction_type'),
        ('goals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goals.goal', verbose_name='Meta'),
        ),
    ]
