# Generated by Django 6.0.6 on 2026-06-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_add_goal_to_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('INCOME', 'Ingreso'), ('EXPENSE', 'Gasto')], db_index=True, max_length=7, verbose_name='Tipo'),
        ),
    ]
