# Generated by Django 6.0.6 on 2026-08-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_alter_transaction_date_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='rates_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cotizaciones actualizadas'),
        ),
    ]
