# Generated by Django 6.0.6 on 2026-08-06 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_currency_rates_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='custom_tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
