# Generated by Django 6.0.6 on 2026-08-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_remove_transaction_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_recurring',
        ),
    ]
