# Generated by Django 6.0.6 on 2026-08-17 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0011_rename_transaction_goal_to_reserve'),
        ('goals', '0003_rename_goal_to_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reserve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goals.reserve', verbose_name='Reserva'),
        ),
    ]
